### PR TITLE
close #20

### LINKED ISSUE #20: popup menu not aligned
screen shot 2017-05-16 at 7 57 09 pm

@Gammaalpha hey mind working on this issue? this needs margins so it dosnt stick to the side and comes out of alittle bit when clicking on the three dot icon

this build is in a detailspageWIP branch

### PR DESCRIPTION
**Pull request by Gammaalpha**
Got the Padding working so accept this pull request. Please ignore the previous pull request. I was testing something and did something dumb.

### CODE REVIEW

**Comment by davidhuang1550** [comment]
@Gammaalpha can you change the name of this pr to close (closes #20 ) remove the brackets. also the if u push a change to the branch u made the pr with the it will automatically update the pr.

**Comment by davidhuang1550** [comment]
@Gammaalpha why did u close this issue?

**Comment by davidhuang1550** [comment]
@Gammaalpha  i want to take it i just want it to reference the issue so when i merge it will automatically close the issue.

**Comment by Gammaalpha** [comment]
I assumed you wanted me to close it since you said to name it close.

**Comment by davidhuang1550** [comment]
@Gammaalpha  add the issue number

**Comment by Gammaalpha** [comment]
Like that?

**Pull request merged**
